[package]
name = "feanor_la"
version = "0.1.0"
authors = ["Simon Pohmann <simon@pohmann.de>"]
edition = "2018"

[lib]
crate-type = ["rlib"]
bench = true

[dependencies]
oorandom = "11.1.3"
take_mut = "0.2.2"
array-init = "2.0.0"